/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: 'var(--paper)',
        surface: 'var(--surface)',
        raised: 'var(--raised)',
        sunken: 'var(--sunken)',
        panel: 'var(--panel)',
        line: 'var(--line)',
        'line-strong': 'var(--line-strong)',
        ink: 'var(--ink)',
        'ink-2': 'var(--ink-2)',
        'ink-3': 'var(--ink-3)',
        'ink-4': 'var(--ink-4)',
        'on-ink': 'var(--on-ink)',
        hv: 'var(--hv)',
        'hv-dim': 'var(--hv-dim)',
        'hv-ink': 'var(--hv-ink)',
        ok: 'var(--ok)',
        'ok-bg': 'var(--ok-bg)',
        warn: 'var(--warn)',
        'warn-bg': 'var(--warn-bg)',
        bad: 'var(--bad)',
        'bad-bg': 'var(--bad-bg)',
        info: 'var(--info)',
        'info-bg': 'var(--info-bg)',
        purple: 'var(--purple)',
        'purple-bg': 'var(--purple-bg)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Archivo', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.01em' }],
        xs: ['0.75rem', { lineHeight: '1.125rem' }],
        sm: ['0.8125rem', { lineHeight: '1.25rem' }],
        base: ['0.875rem', { lineHeight: '1.375rem' }],
        md: ['0.9375rem', { lineHeight: '1.5rem' }],
        lg: ['1.0625rem', { lineHeight: '1.5rem' }],
        xl: ['1.25rem', { lineHeight: '1.6rem', letterSpacing: '-0.011em' }],
        '2xl': ['1.5rem', { lineHeight: '1.8rem', letterSpacing: '-0.018em' }],
        '3xl': ['1.875rem', { lineHeight: '2.1rem', letterSpacing: '-0.022em' }],
        '4xl': ['2.375rem', { lineHeight: '2.5rem', letterSpacing: '-0.026em' }],
      },
      borderRadius: { xs: '3px', sm: '5px', DEFAULT: '7px', md: '9px', lg: '12px', xl: '16px' },
      boxShadow: {
        xs: '0 1px 2px -1px var(--shadow-1)',
        sm: '0 1px 2px -1px var(--shadow-1), 0 2px 6px -2px var(--shadow-1)',
        md: '0 2px 4px -2px var(--shadow-1), 0 8px 20px -6px var(--shadow-2)',
        lg: '0 4px 8px -4px var(--shadow-1), 0 24px 48px -12px var(--shadow-2)',
        pop: '0 0 0 1px var(--line), 0 8px 28px -8px var(--shadow-2), 0 2px 6px -2px var(--shadow-1)',
      },
      transitionTimingFunction: {
        out: 'cubic-bezier(0.22, 1, 0.36, 1)',
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        'toast-in': { from: { opacity: '0', transform: 'translateY(10px) scale(0.98)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        sweep: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(400%)' } },
        shimmer: { '100%': { transform: 'translateX(100%)' } },
        'pulse-dot': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.35' } },
      },
      animation: {
        'fade-in': 'fade-in 180ms cubic-bezier(0.22,1,0.36,1) both',
        'slide-up': 'slide-up 220ms cubic-bezier(0.22,1,0.36,1) both',
        'slide-in-right': 'slide-in-right 260ms cubic-bezier(0.16,1,0.3,1) both',
        'toast-in': 'toast-in 260ms cubic-bezier(0.16,1,0.3,1) both',
        sweep: 'sweep 1.6s cubic-bezier(0.4,0,0.6,1) infinite',
        shimmer: 'shimmer 1.6s infinite',
        'pulse-dot': 'pulse-dot 1.6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
